@echo off
echo [xqshare] Killing processes on port 18812...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :18812 ^| findstr LISTENING') do (
    echo [xqshare] Killing PID=%%a...
    taskkill /F /PID %%a
)
echo [xqshare] Waiting for port release...
timeout /t 2 >nul
echo [xqshare] Starting xqshare service with veighna_studio Python (xtquant)...
cd /d C:\Users\James
start "xqshare" "C:\veighna_studio\python.exe" -m xqshare.server --host 0.0.0.0 --port 18812
echo [xqshare] Done.